name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: novotestapp

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file src/NovoTestApp/Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.AZURE_PASS }}" | docker login gawlas.azurecr.io -u gawlas --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=gawlas.azurecr.io/nonotestapp/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          # Name of the Resource Group in which the Container Instance will be created
          resource-group: demo
          # Number of CPU Cores Required
          cpu: 1 # optional, default is 1
          # The DNS Name Label for Container with Public IP
          dns-name-label: novotestapp
          # Specify the fully qualified container image name. For example, "myregistry.azurecr.io/nginx:latest" or "python:3.7.2-alpine/"
          image: $IMAGE_ID:$VERSION
          # Location where the Container will be deployed
          location: northeurope
          # Required Memory of the Containers in GB, accurate to one decimal place
          memory: 0.5 # optional, default is 1.5
          # Name of the Container Group Instance
          name: novotestapp
          # The OS type of the Containers. Accepted Values are  { Linux, Windows }
          os-type: linux # optional, default is Linux
          # The Ports to Open on the Container. Space seperate the ports for multiple values
          ports: 80 # optional, default is 80
          # The Network protocol to use. Accepted Values are { TCP, UDP }
          protocol: TCP # optional, default is TCP
          # The container image registry login server
          registry-login-server: gawlas.azurecr.io 
          # Username to log in Container Image Registry Server
          registry-username: gawlas 
          # Password to log in Container Image Registry Server
          registry-password: ${{ secrets.AZURE_PASS }} # optional, default is 